categories_kw = {
    "Operational Efficiency": {
        "staff", "service", "waiter", "waitress", "server", "hostess", "bartender",
        "manager", "management", "crew", "employee", "team", "hospitality", "attentive",
        "friendly", "rude", "unprofessional", "slow", "fast", "efficient", "wait",
        "delay", "book", "reserv", "order", "deliver", "check", "attitude",
        "polite", "helpful", "ignored", "neglected", "disinterested", "line", "queue", "speed",
        "welcom", "greet", "seat", "assist", "respond", "communicat", "courteous", "prompt",
        "incompetent", "inexperienced", "trained", "untrained", "professional", "rushed",
        "patient", "impatient", "acknowledge", "interrupt", "dismiss", "arrogant", "condescending",
        "warm", "cold", "indifferent", "overwhelmed", "understaffed", "overstaffed", "short-staffed",
        "shift", "supervisor", "owner", "cashier", "receptionist", "concierge", "agent", "rep",
        "representative", "advisor", "consultant", "technician", "specialist", "support", "helpdesk",
        "operator", "associate", "clerk", "attendant", "guard", "security", "coordinator",
        "turnover", "mistake", "error", "mix-up", "apolog", "compensat", "escalat",
        "refund", "complaint", "feedback", "resolution", "follow-up", "proactive", "reactive",
        "forgot", "missing", "late", "early", "on time", "punctual", "chaotic",
        "organized", "disorganized", "smooth", "seamless", "hassle", "straightforward",
        "appointment", "schedule", "cancel", "reschedule", "no-show", "walk-in", "availability",
        "response time", "wait time", "hold", "callback", "ticket", "request", "inquiry",
        "onboarding", "offboarding", "handover", "transfer", "escalation", "protocol",
        "knowledgeable", "clueless", "upsell", "pushy", "transparent", "mislead", "honest",
        "trustworthy", "unreliable", "dependable", "consistent", "inconsistent"
    },
    "Value Proposition": {
        "price", "cost", "expensive", "cheap", "affordable", "value", "worth",
        "overpriced", "deal", "discount", "budget", "bill", "receipt", "rip-off",
        "pricy", "economical", "steep", "charge", "fee", "wallet", "penny",
        "premium", "reasonable", "extortionate", "bank", "bucks", "spend", "paid", "pay",
        "money", "cash", "credit", "total", "amount", "costly", "inexpensive",
        "bargain", "splurge", "luxury", "mid-range", "upscale", "budget-friendly",
        "rip off", "value for money", "justified", "unjustified", "markup", "hidden",
        "surcharge", "tax", "service charge", "subscription", "membership", "tier",
        "plan", "package", "bundle", "contract", "quote", "estimate", "invoice", "rate",
        "hourly", "monthly", "annual", "one-time", "recurring", "flat", "variable",
        "commission", "interest", "penalty", "fine", "overage", "extra", "add-on",
        "promotion", "coupon", "voucher", "loyalty", "reward", "cashback", "rebate",
        "free", "complimentary", "included", "excluded", "trial", "freemium",
        "comparison", "competitor", "elsewhere", "cheaper elsewhere", "not worth", "worth it",
        "bang for buck", "return on investment", "roi", "saving", "overcharge", "undercharge",
        "transparent pricing", "hidden fees", "no hidden", "surprise charge", "unexpected"
    },
    "Physical Environment": {
        "atmosphere", "vibe", "ambience", "interior", "decor", "design", "lighting",
        "music", "noise", "loud", "quiet", "clean", "dirty", "messy", "bathroom",
        "restroom", "toilet", "seating", "table", "chair", "crowded", "spacious",
        "parking", "location", "ac", "heating", "smell", "aesthetic", "cozy", "dark", "bright",
        "temperature", "hot", "cold", "warm", "freezing", "stuffy", "airy", "ventilat",
        "outdoor", "indoor", "patio", "terrace", "rooftop", "lobby", "reception", "waiting room",
        "office", "store", "shop", "clinic", "salon", "gym", "studio", "facility", "venue",
        "floor", "wall", "ceiling", "decoration", "theme", "layout", "space", "area", "zone",
        "modern", "vintage", "rustic", "minimalist", "elegant", "trendy", "dated", "outdated",
        "renovated", "worn", "run-down", "well-maintained", "maintained", "neglected", "dilapidated",
        "sanitize", "hygiene", "hygienic", "germ", "pest", "odor", "stench", "fresh",
        "wifi", "internet", "signal", "connection", "screen", "display", "monitor", "equipment",
        "accessible", "wheelchair", "disabled", "elevator", "lift", "ramp", "stairs",
        "family-friendly", "kid-friendly", "pet-friendly", "child", "baby",
        "distance", "nearby", "convenient", "central", "hidden", "hard to find", "easy to find",
        "neighborhood", "area", "district", "transport", "transit", "bus", "subway", "parking lot",
        "entrance", "exit", "sign", "visible", "privacy", "private", "open plan", "booth",
        "safe", "unsafe", "security", "cctv", "surveillance", "well-lit", "poorly lit",
        "building", "premises", "grounds", "courtyard", "corridor", "hallway", "room"
    },
    "Product/Offering": {
        "quality", "taste", "flavor", "delicious", "tasty", "yummy", "disgusting",
        "bland", "fresh", "stale", "frozen", "portion", "size", "menu", "selection",
        "variety", "option", "drink", "food", "beverage", "meal", "dish", "presentation",
        "cook", "raw", "burnt", "authentic", "recipe", "ingredient", "sauce",
        "product", "item", "goods", "stock", "inventory", "range", "catalog", "collection",
        "model", "version", "edition", "variant", "specification", "feature", "function",
        "performance", "result", "outcome", "effect", "output", "efficacy", "effective",
        "durable", "durability", "lasting", "broke", "broken", "defective", "faulty", "damaged",
        "reliable", "unreliable", "consistent", "inconsistent", "accurate", "inaccurate",
        "innovative", "outdated", "cutting-edge", "state-of-the-art", "basic", "advanced",
        "user-friendly", "intuitive", "complicated", "confusing", "easy to use", "hard to use",
        "software", "hardware", "app", "platform", "tool", "system", "device", "machine",
        "treatment", "procedure", "therapy", "session", "class", "course", "program", "workshop",
        "curriculum", "content", "material", "resource", "module", "lesson", "training",
        "package", "service package", "offering", "solution", "deliverable", "project",
        "customiz", "personaliz", "tailor", "bespoke", "standard", "generic", "one-size",
        "upgrade", "downgrade", "update", "patch", "fix", "improvement", "regression",
        "limit", "restriction", "capabilit", "compatib", "integrat", "support", "maintenance",
        "warranty", "guarantee", "return", "exchange", "replacement", "spare", "part",
        "new", "used", "second-hand", "refurbished", "original", "counterfeit", "fake", "genuine"
    },
}

umbrella_words = {
    "Operational Efficiency": {
        "staff", "service", "employee", "team", "crew", "management", "personnel",
    },
    "Value Proposition": {
        "price", "cost", "pric", "money", "pay", "paid", "fee", "charge", "bill",
    },
    "Physical Environment": {
        "location", "area", "space", "place", "venue", "facility", "environment",
    },
    "Product/Offering": {
        "product", "item", "offering", "option", "selection", "feature",
    },
}